### ISSUE TITLE
gen_patch.problem on saving patches to file

### ISSUE THREAD

**Issue by wenmengliu** [veugene/lits#2]
Hi Veugene,

I input `data_tools` into my python path, which could work for me. Now I have trouble with the following error as attach. I tried to figure it out by myself but I failed. Hopefully you can help me with it.
My python version is 3.6. What is the python version for data_tools?

![minor_error_for_me](https://user-images.githubusercontent.com/11565143/45924955-cac97a00-bec0-11e8-98b4-8798f1e39284.jpg)

**Comment by wenmengliu** [comment]
By the way, I also modified one thing for gen_patches. Because when I run it, there was an issue about operator problem. My commit screenshot is attached. Please kindly give me your feedbacks!
<img width="985" alt="mycommit" src="https://user-images.githubusercontent.com/11565143/45924973-20058b80-bec1-11e8-86db-e03abeaa6c3d.png">

**Comment by wenmengliu** [comment]
And my h5py version info is below:
Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.10.2
Python  3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.14.3

I am still working on this issue and haven't resolved it yet.

**Comment by wenmengliu** [comment]
After constantly trying, I finally make it! Here is my commit below. 
<img width="1011" alt="screen shot 2018-09-23 at 4 46 49 pm" src="https://user-images.githubusercontent.com/11565143/45934242-6fdf6380-bf50-11e8-89ed-14d40a78b7a1.png">

**Comment by veugene** [comment]
Thanks! Looks like it's an issue in the buffered array writers in `data_tools.io`. Fixed now, in that repo, in https://github.com/veugene/data_tools/pull/3

A note on the code in this repo, by the way: this repository was never cleaned up, documented, or intended for a proper release. It's just the repository I was working on when working on LiTS. I switched it from private to public in case anyone would like to check my code. While this could be a useful reference, I suggest using [fcn_maker](https://github.com/veugene/fcn_maker/tree/pytorch/fcn_maker) and [data_tools](https://github.com/veugene/data_tools) to build models and set up experiments as I maintain those code bases and released them with documentation.

I linked to the pytorch version of fcn_maker but there is also the keras version in the master branch, with theano and tensorflow backends supported.

**Comment by wenmengliu** [comment]
Thanks for your advice!! This repo is really a good reference for me, a new beginner for medical image analysis. I would take your advice and try to set up the model. I am so curious about the experiments :). This whole process can make me learn so fast. Anyway, thanks for your great work, Veugene!!
